bundle:
  js:
    - /js/element.js
    - /js/client.js
    - /js/window.js
    - /js/app.js
  css:
    - /css/base.css
    - /css/app.css
    - /css/account.css
    - /css/tags.css
    - /css/dialog.css
    - /css/form.css
    - /css/loader.css
    - /css/spinner.css
